# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  paths:
     include:
      - result/* 

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '1e402072-83a6-4563-98f7-4d9a9d67ce7d'
  imageRepository: 'sikharamexamplevotingapp'
  containerRegistry: 'susmithacr.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/result/Dockerfile'
  tag: '$(Build.BuildId)'
pool:
   name: 'azureagent'
stages:
- stage: Build
  displayName: Build the image
  jobs:
  - job: Build
    displayName: Build
    steps:
    - task: Docker@2
      displayName: Build an image to container registry
      inputs:
        command: build
        repository: $(imageRepository)
        dockerfile: 'result/Dockerfile'
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)
  - job: push
    displayName: push
    steps:
    - task: Docker@2
      displayName: Build an image to container registry
      inputs:
        command: push
        repository: $(imageRepository)
        dockerfile: 'result/Dockerfile'
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)
